services:
  postgres:
    image: postgres:16.4
    container_name: user_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
